### ISSUE TITLE
Add NL-RSE video to the home page

### ISSUE THREAD

**Issue by ctwhome** [nl-rse/website#12]
I made three sketches. Which one do you like most? any other alternative?

![](https://user-images.githubusercontent.com/4195550/137442182-a51888f7-a289-4eb4-9a2b-5abaabb0fa03.png)

![](https://user-images.githubusercontent.com/4195550/137442203-727fbe76-e172-484f-aeb3-7905b3dd050f.png)

![](https://user-images.githubusercontent.com/4195550/137442243-95437203-9d93-4fe9-babd-b8f19b140847.png)

**Comment by tbkkr** [comment]
I think #1.

**Comment by c-martinez** [comment]
I was thinking it could be a carousel https://getbootstrap.com/docs/4.0/components/carousel/ ? (and pause its movement when video is playing)
