### ISSUE TITLE
Add RSS feed

### ISSUE THREAD

**Issue by c-martinez** [nl-rse/website#3]
Previously there was a suggestion for having an RSS feed, and/or iCalendar feed (see https://github.com/nl-rse/nl-rse.github.io/issues/76) -- does the new style support either of these (or both?)

**Comment by c-martinez** [comment]
And if this is possible, maybe we should add links to feeds somewhere? At the moment finding https://nl-rse.org/feed.xml requires knowing it is there :-)

**Comment by ctwhome** [comment]
🎉 I just deployed the rss feed with a mix of events plus blogpost, ordered by date here: https://nl-rse.netlify.app/feed.xml
see the commit here: https://github.com/nl-rse/website/commit/f3b6e51b872becf4c3cab5c20571a50095e28cea
 I will made another issue for the iCalendar

**Comment by ctwhome** [comment]
added a link to the footer 

![](https://user-images.githubusercontent.com/4195550/125517028-a0270e77-d19b-466a-a82e-30e6e8ff52ee.png)

**Comment by c-martinez** [comment]
Awesome!
