### ISSUE TITLE
Create a page that shows an overview of RSE groups in the Netherlands

### ISSUE THREAD

**Issue by liekelotte** [nl-rse/website#65]
What would be the best way of displaying these? People filled out our template issue, it would be nice to have an overview including a map maybe (if possible) but not sure how hard that is to do? What do you think?

**Comment by ctwhome** [comment]
We could create something like the team page, with cards and managed by markdown? 
A map could also be possible if we have the coordinates.

**Comment by liekelotte** [comment]
I think that's a nice idea. We don't have coordinates but we do have the institutes, so adding coordinates hopefully isn't too complicated.

**Comment by ctwhome** [comment]
we could start with the cards and eventually add the map

**Comment by c-martinez** [comment]
I like the idea of having a map, and getting the coordinates shouldn't be much of an issue. We could even query Wikidata to fetch information from there: https://www.wikidata.org/wiki/Q214341

**Comment by liekelotte** [comment]
If we can automate the generation of json file from the template issue (see https://github.com/zachleat/github-issue-to-json-file#step-2-add-the-github-actions-workflow-file), @ctwhome says he can easily create the page. @DaanVanVugt do you think this is something thats relatively straightforward for you to do?

**Comment by DaanVanVugt** [comment]
I think we may not have enough entries to automate it in this way, a bit of manual work per issue would be optimal at this point I think

**Comment by liekelotte** [comment]
does the number of entries matter? doesnt the github action get triggered per (opened/modified) issue? so 1 json file, 1 issue?

**Comment by DaanVanVugt** [comment]
Well it's mostly about the engineering effort to automate this, compared to the manual effort to fill in a json template (and to have the opportunity to inspect the text before going on our website)

**Comment by liekelotte** [comment]
Ah, I was hoping enabling the GH action would be about the same as 1 manual json file creation (and then automatically generated json files would still have to be inspected, of course - just to be sure)
