### ISSUE TITLE
incorporate tillidium web into new logo

### ISSUE THREAD

**Issue by liekelotte** [nl-rse/website#9]

**Comment by ctwhome** [comment]
I need to prepare the final logo resources with the new Tillidium Web font

**Comment by ctwhome** [comment]
done! See logos here [NL-RSE Logo - OneDrive (sharepoint.com)](https://nlesc-my.sharepoint.com/personal/j_g_gonzalez_esciencecenter_nl/_layouts/15/onedrive.aspx?originalPath=aHR0cHM6Ly9ubGVzYy1teS5zaGFyZXBvaW50LmNvbS86ZjovZy9wZXJzb25hbC9qX2dfZ29uemFsZXpfZXNjaWVuY2VjZW50ZXJfbmwvRXJ1d1hPSjVadVpIc3UyNXJ0MmVSbUFCaTYtaWVKZDNXQ3NzVVR5ay1ES0QtZz9ydGltZT1VQ0JVVmh4NTJVZw&sortField=LinkFilename&isAscending=true&id=%2Fpersonal%2Fj%5Fg%5Fgonzalez%5Fesciencecenter%5Fnl%2FDocuments%2FNL%2DRSE%20Logo)
